const EMPTY = [];

const SMALL = [
  {
    id: "1",
    imageSource: "/images/4-fromage.jpg",
    title: "4 Fromages",
    price: 14.898,
    description:
      "Sauce tomate à l'origan ou crème fraîche légère, mozzarella, fromage de chèvre, emmental et Fourme d'Ambert AOP",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/chevre-miel.jpg",
    title: "Chèvre Miel",
    price: 12.8985,
    description: "Crème fraîche légère, mozzarella, fromage de chèvre, miel",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/images/la-parmigiano.jpg",
    title: "Parmigiano",
    price: 11.897,
    description:
      "Sauce tomate à l'origan, mozzarella, tomates fraîches, parmigiano reggiano AOP",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const FULL = [
  {
    id: "1",
    imageSource: "/images/4-fromage.jpg",
    title: "4 Fromages",
    price: 14.898,
    description:
      "Sauce tomate à l'origan ou crème fraîche légère, mozzarella, fromage de chèvre, emmental et Fourme d'Ambert AOP",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/chevre-miel.jpg",
    title: "Chèvre Miel",
    price: 12.8985,
    description: "Crème fraîche légère, mozzarella, fromage de chèvre, miel",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/images/la-parmigiano.jpg",
    title: "Parmigiano",
    price: 11.897,
    description:
      "Sauce tomate à l'origan, mozzarella, tomates fraîches, parmigiano reggiano AOP",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/merguez-poulet.jpg",
    title: "Carnivore",
    price: 15.898,
    description:
      "Sauce barbecue, mozzarella, emietté au boeuf, Poulet rôti et merguez",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "5",
    imageSource: "/images/montagnarde.jpg",
    title: "Montagnarde",
    price: 14.897,
    description:
      "Crème fraîche légère, mozzarella, jambon cru, fromage à raclette et champignons frais",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/images/orientale.jpg",
    title: "Orientale",
    price: 13.896,
    description:
      "Sauce tomate à l'origan, mozzarella, merguez et champignons frais",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/images/pepperoni.jpeg",
    title: "Pepperoni Lovers",
    price: 13.897,
    description: "Sauce tomate à l'origan, mozzarella et saucisse pepperoni",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "8",
    imageSource: "/images/queen.jpg",
    title: "Queen",
    price: 14.8978,
    description:
      "Sauce tomate à l'origan, mozzarella, jambon et champignons frais",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/images/raclette.jpg",
    title: "Raclette",
    price: 16.899,
    description:
      "Crème fraîche légère, mozzarella, pommes de terre, lardons et fromage à raclette",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/images/supreme.jpg",
    title: "Supreme",
    price: 15.898,
    description:
      "Sauce tomate à l'origan, mozzarella, emietté au boeuf, saucisse pepperoni, champignons frais, oignons rouges frais et poivrons.",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "11",
    imageSource: "/images/texane-barbecue.jpg",
    title: "Texane",
    price: 12.898,
    description:
      "Sauce barbecue, mozzarella, jambon, emietté au boeuf, lardons, champignons frais et oignons rouges frais.",
    isVegetarian: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "12",
    imageSource: "/images/vegetarienne.jpg",
    title: "Veggie",
    price: 13.898,
    description:
      "Sauce tomate à l'origan, mozzarella, champignons frais, oignons rouges frais, poivrons verts frais, tomates fraîches et Olives noires",
    isVegetarian: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const MenuData = {
  EMPTY,
  SMALL,
  FULL,
};
