export const fakeMenu1 = [
  {
    id: 1,
    imageSource: "/images/burger1.png",
    title: "Burger 1",
    price: 5.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/burger2.png",
    title: "Burger 2",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const fakeMenu2 = [
  {
    id: 1,
    imageSource: "/images/4-fromage.jpg",
    title: "4 Fromages",
    price: 14.598,
    description:
      "Sauce tomate à l'origan ou crème fraîche légère, mozzarella, fromage de chèvre, emmental et Fourme d'Ambert AOP",
    vegetarien: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: "/images/chevre-miel.jpg",
    title: "Chèvre Miel",
    price: 12.4985,
    description: "Crème fraîche légère, mozzarella, fromage de chèvre, miel",
    vegetarien: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: "/images/la-parmigiano.jpg",
    title: "Parmiggiano",
    price: 11.367,
    description:
      "Sauce tomate à l'origan, mozzarella, tomates fraîches, parmigiano reggiano AOP",
    vegetarien: true,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: "/images/merguez-poulet.jpg",
    title: "Chicken Merguez",
    price: 15.568,
    description:
      "Sauce barbecue, mozzarella, emietté au boeuf, Poulet rôti et merguez",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: "/images/montagnarde.jpg",
    title: "Montagnarde",
    price: 14.487,
    description:
      "Crème fraîche légère, mozzarella, jambon cru, fromage à raclette et champignons frais",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    imageSource: "/images/orientale.jpg",
    title: "Orientale",
    price: 13.356,
    description:
      "Sauce tomate à l'origan, mozzarella, merguez et champignons frais",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    imageSource: "/images/pepperoni.jpeg",
    title: "Pepperoni Lovers",
    price: 13.567,
    description: "Sauce tomate à l'origan, mozzarella et saucisse pepperoni",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 8,
    imageSource: "/images/queen.jpg",
    title: "Queen",
    price: 14.1678,
    description:
      "Sauce tomate à l'origan, mozzarella, jambon et champignons frais",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 9,
    imageSource: "/images/raclette.jpg",
    title: "Raclette",
    price: 16.7,
    description:
      "Crème fraîche légère, mozzarella, pommes de terre, lardons et fromage à raclette",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 10,
    imageSource: "/images/supreme.jpg",
    title: "Supreme",
    price: 15.678,
    description:
      "Sauce tomate à l'origan, mozzarella, emietté au boeuf, saucisse pepperoni, champignons frais, oignons rouges frais et poivrons verts frais",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 10,
    imageSource: "/images/texane-barbecue.jpg",
    title: "Texane",
    price: 12.678,
    description:
      "Sauce barbecue, mozzarella, jambon, emietté au boeuf, lardons, champignons frais et oignons rouges frais.",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 10,
    imageSource: "/images/vegetarienne.jpg",
    title: "Veggie",
    price: 13.678,
    description:
      "Sauce tomate à l'origan, mozzarella, champignons frais, oignons rouges frais, poivrons verts frais, tomates fraîches et Olives noires",
    vegetarien: false,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];
